# Pythonaibrain — Funding
# Author: Divyanshu Sinha
# https://github.com/DivyanshuSinha136

github: [DivyanshuSinha136]
patreon: # not set
open_collective: # not set
ko_fi: # not set
tidelift: pypi/pythonaibrain
community_bridge: # not set
liberapay: # not set
issuehunt: # not set
lfx_crowdfunding: # not set
polar: # not set
buy_me_a_coffee: # not set
thanks_dev: # not set
custom: # not set
